# Site settings
title: Robert Baur
description: Street Photography
baseurl: ""
url: "https://Robert-Street-Photgraphy.github.io"
author: Robert Baur

# Collection settings
collections:
  photos:
    output: true

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
